import {
  IconAlertTriangle,
  IconArrowBackUp,
  IconArrowsHorizontal,
  IconAt,
  IconBadges,
  IconBook2,
  IconBookDownload,
  IconBooks,
  IconBrandGithub,
  IconBrandTelegram,
  IconBrightnessHalf,
  IconBrush,
  IconCalendar,
  IconCalendarCheck,
  IconChartLine,
  IconChevronRight,
  IconClock,
  IconCoins,
  IconDatabase,
  IconDownload,
  IconEraser,
  IconExchange,
  IconFilePencil,
  IconFileText,
  IconGitBranch,
  IconHash,
  IconHexagon,
  IconHistory,
  IconIndentIncrease,
  IconInfoCircle,
  IconLanguage,
  IconLayoutColumns,
  IconLayoutDashboard,
  IconLayoutList,
  IconLineHeight,
  IconLogout,
  IconMail,
  IconNumber1,
  IconNumber2,
  IconNumber3,
  IconNumber4,
  IconNumber5,
  IconNumber6,
  IconPackageImport,
  IconPalette,
  IconPhoto,
  IconPhotoCircle,
  IconRefresh,
  IconRobot,
  IconSearch,
  IconSettings,
  IconShoppingBag,
  IconSpeakerphone,
  IconTag,
  IconTextSize,
  IconTicket,
  IconTrash,
  IconTrophy,
  IconUserCircle,
  IconUsers,
  IconUsersGroup,
  IconWorld,
} from '@tabler/icons-react-native';
import type { ComponentProps, ComponentType } from 'react';

import type { NativeIconName } from '@/components/native-icon-types';

export type TablerNativeIcon = ComponentType<ComponentProps<typeof IconUserCircle>>;

export const tablerNativeIcons: Record<NativeIconName, TablerNativeIcon> = {
  account: IconUserCircle,
  aiContent: IconRobot,
  announcement: IconSpeakerphone,
  appUpdate: IconRefresh,
  appearance: IconPalette,
  avatar: IconPhotoCircle,
  badgeAi: IconRobot,
  badges: IconBadges,
  badgeEdit: IconFilePencil,
  badgeFilter1: IconNumber1,
  badgeFilter2: IconNumber2,
  badgeFilter3: IconNumber3,
  badgeFilter4: IconNumber4,
  badgeFilter5: IconNumber5,
  badgeFilter6: IconNumber6,
  badgeHistory: IconHistory,
  badgeJapanese: IconBook2,
  badgeLevel: IconHexagon,
  badgeReply: IconArrowBackUp,
  badgeTranslate: IconLanguage,
  bookDetailCache: IconBookDownload,
  books: IconBooks,
  cache: IconDatabase,
  changelogs: IconGitBranch,
  checkIn: IconCalendarCheck,
  coins: IconCoins,
  chevronRight: IconChevronRight,
  clearFontCache: IconEraser,
  clearImageCache: IconTrash,
  clock: IconClock,
  comicPageLayout: IconLayoutColumns,
  community: IconUsers,
  content: IconLayoutDashboard,
  continueReading: IconClock,
  coverColor: IconBrush,
  discover: IconBook2,
  email: IconMail,
  error: IconAlertTriangle,
  firstLineIndent: IconIndentIncrease,
  experience: IconChartLine,
  fontCache: IconFileText,
  fontCacheLimit: IconDatabase,
  imagePreview: IconPhoto,
  info: IconInfoCircle,
  inviteCode: IconTicket,
  japanese: IconLanguage,
  language: IconLanguage,
  level6Content: IconHexagon,
  level: IconHexagon,
  lineHeight: IconLineHeight,
  preload: IconDownload,
  profileError: IconAlertTriangle,
  profileStatus: IconUserCircle,
  progress: IconRefresh,
  reader: IconBook2,
  readerTitle: IconBook2,
  readingDirection: IconArrowsHorizontal,
  readingMode: IconLayoutList,
  ranking: IconTrophy,
  registered: IconCalendar,
  search: IconSearch,
  seriesSearch: IconSearch,
  settings: IconSettings,
  shop: IconShoppingBag,
  sidePadding: IconArrowsHorizontal,
  sideload: IconPackageImport,
  signOut: IconLogout,
  sourceCode: IconBrandGithub,
  telegram: IconBrandTelegram,
  textConvert: IconExchange,
  textSize: IconTextSize,
  theme: IconBrightnessHalf,
  uid: IconHash,
  userGroup: IconUsersGroup,
  userName: IconAt,
  version: IconTag,
  website: IconWorld,
};
